jaffle_shop:
  outputs:
    dev:
      dataset: {{BIGQUERY_DATASET}}
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: {{PATH_TO_KEYFILE}}
      location: US
      method: service-account
      priority: interactive
      project: {{GCP_PROJECT}}
      threads: 1
      type: bigquery
  target: dev
